name: CI
on: [push, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle-version:
          - "7.6.4"
          - "8.0"
          - "8.14"
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: ".java-version"

      - name: Build and test
        env:
          GRADLE_VERSION: ${{ matrix.gradle-version }}
        run: ./gradlew clean test

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "build/test-results/**/*.xml"

      - name: Lint
        run: ./gradlew check -x test

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: build/reports/jacoco/test
          dry_run: false
          verbose: false
