name: CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: ".java-version"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and test
        run: ./gradlew clean build -x ktlintMainSourceSetCheck -x ktlintMainSourceSetFormat -x ktlintTestSourceSetCheck -x ktlintTestSourceSetFormat
        continue-on-error: true

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "build/test-results/**/*.xml"

      - name: Lint
        run: ./gradlew ktlintFormat ktlintCheck

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: build/reports/jacoco/test
          dry_run: false
          verbose: false
