name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: "This issue is stale and will be closed in 5 days."
          stale-pr-message: "This PR is stale and will be closed in 5 days."
          days-before-stale: 30
          days-before-close: 5
          any-of-labels: "waiting-feedback"
          exempt-all-milestones: true
          debug-only: false
          enable-statistics: true